### PR TITLE
Süle Kata - Opt-out Exam Solutions

### PR DESCRIPTION
**Pull request by sulekata**
Dear Olivér,

please find the solutions for the IT as well as the Math tasks.

Kind regards,
Kata

### CODE REVIEW

**Comment by kiss-oliver** [comment]
Thank you for your submission, you've passed the opt-out exam.

**Comment by sulekata** [comment]
Thank you! Despite having passed the exam would it still be possible for me
to attend the pre-session?

Olivér Kiss <notifications@github.com> ezt írta (időpont: 2020. aug. 30.,
V, 19:25):

**Comment by kiss-oliver** [comment]
@sulekata Sure, it's open to everyone in the program.

**Comment by sulekata** [comment]
Thank you!

**Pull request closed without merging**
